name: Warn scheduled workflow
description: "Warn if scheduled workflow is about to be disabled due to the following GitHub policy: In a public repository, scheduled workflows are automatically disabled when no repository activity has occurred in 60 days"

inputs:
  workflow-filename:
    description: Filename of the workflow, without the leading .github/workflows prefix.
    required: true
  main-branch:
    description: Name of the default branch.
    required: false
    default: main
  days-elapsed:
    description: Number of days elapsed from the previous repository activity to raise the warning.
    required: true
  token:
    description: Token of the user to be provided to GiHub API.
    required: false
    default: ""

runs:
  using: "composite"
  steps:
    - name: Install dependencies
      run: |
        pip3 -q install -r ${GITHUB_ACTION_PATH}/scripts/requirements.txt
      shell: bash
    - name: Warn if scheduled workflow is about to be disabled
      run: |
        python3 ${GITHUB_ACTION_PATH}/scripts/warn_workflow.py "${GITHUB_REPOSITORY}" "${{ inputs.workflow-filename }}" "${{ inputs.main-branch }}" "${{ inputs.days-elapsed }}" "${{ inputs.token }}"
      shell: bash
