name: CI

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - main
  schedule:
    - cron: "0 0 * * MON"
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          python3 -m pip -q install -r scripts/requirements.txt -r tests/requirements.txt
      - name: Run ruff
        run: |
          python3 -m ruff .
      - name: Run isort
        run: |
          python3 -m isort --check --diff .
      - name: Run mypy
        run: |
          python3 -m mypy .
      - name: Run yamllint
        run: |
          python3 -m yamllint -d "{extends: default, rules: {document-start: {present: false}, line-length: disable, truthy: {check-keys: false}}}" .
      - name: Run tests
        run: |
          python3 -m pytest --token "${{ github.token }}" tests
      - name: Warn if scheduled workflow is about to be disabled
        uses: ./
        with:
          workflow-filename: ci.yml
          days-elapsed: 50
