name: CI

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - main
  schedule:
    - cron: "0 0 * * MON"
  workflow_dispatch:

jobs:
  test_python:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          python3 -m pip install --break-system-packages -q -r scripts/requirements.txt -r tests/requirements.txt
      - name: Run tests
        run: |
          python3 -m pytest --token "${{ github.token }}" tests

  test_action:
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-24.04, ubuntu-22.04, ubuntu-20.04]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Warn if scheduled workflow is about to be disabled
        uses: ./
        with:
          workflow-filename: ci.yml
          days-elapsed: 50

  lint:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          python3 -m pip install --break-system-packages -q -r scripts/requirements.txt -r tests/requirements.txt
      - name: Run ruff
        run: |
          python3 -m ruff check .
      - name: Run isort
        run: |
          python3 -m isort --check --diff .
      - name: Run mypy
        run: |
          python3 -m mypy .
      - name: Run yamllint
        run: |
          python3 -m yamllint -d "{extends: default, rules: {document-start: {present: false}, line-length: disable, truthy: {check-keys: false}}}" .
