name: CI

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - main
  schedule:
    - cron: "0 0 * * MON"
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          python3 -m pip -q install -r scripts/requirements.txt -r tests/requirements.txt
      - name: Run flake8 and mypy checks
        run: |
          python3 -m flake8 .
          python3 -m mypy .
      - name: Run tests
        run: |
          python3 -m pytest --token "${{ github.token }}" tests
      - name: Warn if scheduled workflow is about to be disabled
        uses: ./
        with:
          workflow-filename: ci.yml
          days-elapsed: 50
